# -*- coding: utf-8 -*-
"""Estudo de caso: crescimento da população brasileira.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eByi2L4I4BRl3Qdkaf4jsaYXUKoGt3j7
"""

#Estudo de caso: crescimento da população brasileira
#datasus
import matplotlib.pyplot as plt

dados = open ("populacao-brasileira.csv").readlines()

x=[]
y=[]

for i in range(len(dados)):
  if i != 0:
    linha=dados[i].split(";")
    x.append(int(linha[0]))
    y.append(int(linha[1]))

plt.plot(x, y, color="k" , linestyle="__")
plt.bar(x, y, color ='#e4e4e4')
plt.title("Crescimento da população Brasileira 1980 a 2016")
plt.xlabel("ano")
plt.Ylabel("população x 100.000.000")
#plt.show()
plt.savefig("populaçao_brasileira.png", dpi= 300)